window.esdocSearchIndex = [
  [
    "nutrient-timing-library/models/calorie.js~calories",
    "class/src/models/calorie.js~Calories.html",
    "<span>Calories</span> <span class=\"search-result-import-path\">nutrient-timing-library/models/calorie.js</span>",
    "class"
  ],
  [
    "nutrient-timing-library/models/nutrient.js~carbohydrate",
    "class/src/models/nutrient.js~Carbohydrate.html",
    "<span>Carbohydrate</span> <span class=\"search-result-import-path\">nutrient-timing-library/models/nutrient.js</span>",
    "class"
  ],
  [
    "nutrient-timing-library/models/nutrient.js~fat",
    "class/src/models/nutrient.js~Fat.html",
    "<span>Fat</span> <span class=\"search-result-import-path\">nutrient-timing-library/models/nutrient.js</span>",
    "class"
  ],
  [
    "nutrient-timing-library~models",
    "variable/index.html#static-variable-Models",
    "<span>Models</span> <span class=\"search-result-import-path\">nutrient-timing-library</span>",
    "variable"
  ],
  [
    "nutrient-timing-library/models/nutrient.js~nutrient",
    "class/src/models/nutrient.js~Nutrient.html",
    "<span>Nutrient</span> <span class=\"search-result-import-path\">nutrient-timing-library/models/nutrient.js</span>",
    "class"
  ],
  [
    "nutrient-timing-library/models/profile.js~profile",
    "class/src/models/profile.js~Profile.html",
    "<span>Profile</span> <span class=\"search-result-import-path\">nutrient-timing-library/models/profile.js</span>",
    "class"
  ],
  [
    "nutrient-timing-library/models/nutrient.js~protein",
    "class/src/models/nutrient.js~Protein.html",
    "<span>Protein</span> <span class=\"search-result-import-path\">nutrient-timing-library/models/nutrient.js</span>",
    "class"
  ],
  [
    "nutrient-timing-library~services",
    "variable/index.html#static-variable-Services",
    "<span>Services</span> <span class=\"search-result-import-path\">nutrient-timing-library</span>",
    "variable"
  ],
  [
    "nutrient-timing-library/services/macros.js~calculatecarbohydrate",
    "function/index.html#static-function-calculateCarbohydrate",
    "<span>calculateCarbohydrate</span> <span class=\"search-result-import-path\">nutrient-timing-library/services/macros.js</span>",
    "function"
  ],
  [
    "nutrient-timing-library/services/macros.js~calculatefat",
    "function/index.html#static-function-calculateFat",
    "<span>calculateFat</span> <span class=\"search-result-import-path\">nutrient-timing-library/services/macros.js</span>",
    "function"
  ],
  [
    "nutrient-timing-library/services/macros.js~calculateprotein",
    "function/index.html#static-function-calculateProtein",
    "<span>calculateProtein</span> <span class=\"search-result-import-path\">nutrient-timing-library/services/macros.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/models/calorie.js",
    "file/src/models/calorie.js.html",
    "src/models/calorie.js",
    "file"
  ],
  [
    "src/models/calorie.js~calories#adjustment",
    "class/src/models/calorie.js~Calories.html#instance-method-adjustment",
    "src/models/calorie.js~Calories#adjustment",
    "method"
  ],
  [
    "src/models/calorie.js~calories#base",
    "class/src/models/calorie.js~Calories.html#instance-member-base",
    "src/models/calorie.js~Calories#base",
    "member"
  ],
  [
    "src/models/calorie.js~calories#calculate",
    "class/src/models/calorie.js~Calories.html#instance-method-calculate",
    "src/models/calorie.js~Calories#calculate",
    "method"
  ],
  [
    "src/models/calorie.js~calories#heavy",
    "class/src/models/calorie.js~Calories.html#instance-member-heavy",
    "src/models/calorie.js~Calories#heavy",
    "member"
  ],
  [
    "src/models/calorie.js~calories#light",
    "class/src/models/calorie.js~Calories.html#instance-member-light",
    "src/models/calorie.js~Calories#light",
    "member"
  ],
  [
    "src/models/calorie.js~calories#medium",
    "class/src/models/calorie.js~Calories.html#instance-member-medium",
    "src/models/calorie.js~Calories#medium",
    "member"
  ],
  [
    "src/models/calorie.js~calories#update",
    "class/src/models/calorie.js~Calories.html#instance-method-update",
    "src/models/calorie.js~Calories#update",
    "method"
  ],
  [
    "src/models/index.js",
    "file/src/models/index.js.html",
    "src/models/index.js",
    "file"
  ],
  [
    "src/models/nutrient.js",
    "file/src/models/nutrient.js.html",
    "src/models/nutrient.js",
    "file"
  ],
  [
    "src/models/nutrient.js~nutrient#carbohydrate",
    "class/src/models/nutrient.js~Nutrient.html#instance-member-carbohydrate",
    "src/models/nutrient.js~Nutrient#carbohydrate",
    "member"
  ],
  [
    "src/models/nutrient.js~nutrient#constructor",
    "class/src/models/nutrient.js~Nutrient.html#instance-constructor-constructor",
    "src/models/nutrient.js~Nutrient#constructor",
    "method"
  ],
  [
    "src/models/nutrient.js~nutrient#fat",
    "class/src/models/nutrient.js~Nutrient.html#instance-member-fat",
    "src/models/nutrient.js~Nutrient#fat",
    "member"
  ],
  [
    "src/models/nutrient.js~nutrient#protein",
    "class/src/models/nutrient.js~Nutrient.html#instance-member-protein",
    "src/models/nutrient.js~Nutrient#protein",
    "member"
  ],
  [
    "src/models/nutrient.js~protein#constructor",
    "class/src/models/nutrient.js~Protein.html#instance-constructor-constructor",
    "src/models/nutrient.js~Protein#constructor",
    "method"
  ],
  [
    "src/models/nutrient.js~protein#high",
    "class/src/models/nutrient.js~Protein.html#instance-member-high",
    "src/models/nutrient.js~Protein#high",
    "member"
  ],
  [
    "src/models/nutrient.js~protein#low",
    "class/src/models/nutrient.js~Protein.html#instance-member-low",
    "src/models/nutrient.js~Protein#low",
    "member"
  ],
  [
    "src/models/nutrient.js~protein.fromarray",
    "class/src/models/nutrient.js~Protein.html#static-method-fromArray",
    "src/models/nutrient.js~Protein.fromArray",
    "method"
  ],
  [
    "src/models/nutrient.js~proteinrange",
    "typedef/index.html#static-typedef-ProteinRange",
    "src/models/nutrient.js~ProteinRange",
    "typedef"
  ],
  [
    "src/models/profile.js",
    "file/src/models/profile.js.html",
    "src/models/profile.js",
    "file"
  ],
  [
    "src/models/profile.js~profile#addheightincm",
    "class/src/models/profile.js~Profile.html#instance-method-addHeightInCM",
    "src/models/profile.js~Profile#addHeightInCM",
    "method"
  ],
  [
    "src/models/profile.js~profile#addheightinfeet",
    "class/src/models/profile.js~Profile.html#instance-method-addHeightInFeet",
    "src/models/profile.js~Profile#addHeightInFeet",
    "method"
  ],
  [
    "src/models/profile.js~profile#addweightinkg",
    "class/src/models/profile.js~Profile.html#instance-method-addWeightInKg",
    "src/models/profile.js~Profile#addWeightInKg",
    "method"
  ],
  [
    "src/models/profile.js~profile#age",
    "class/src/models/profile.js~Profile.html#instance-member-age",
    "src/models/profile.js~Profile#age",
    "member"
  ],
  [
    "src/models/profile.js~profile#bmr",
    "class/src/models/profile.js~Profile.html#instance-member-bmr",
    "src/models/profile.js~Profile#bmr",
    "member"
  ],
  [
    "src/models/profile.js~profile#calories",
    "class/src/models/profile.js~Profile.html#instance-member-calories",
    "src/models/profile.js~Profile#calories",
    "member"
  ],
  [
    "src/models/profile.js~profile#constructor",
    "class/src/models/profile.js~Profile.html#instance-constructor-constructor",
    "src/models/profile.js~Profile#constructor",
    "method"
  ],
  [
    "src/models/profile.js~profile#firstname",
    "class/src/models/profile.js~Profile.html#instance-member-firstName",
    "src/models/profile.js~Profile#firstName",
    "member"
  ],
  [
    "src/models/profile.js~profile#height",
    "class/src/models/profile.js~Profile.html#instance-member-height",
    "src/models/profile.js~Profile#height",
    "member"
  ],
  [
    "src/models/profile.js~profile#lastname",
    "class/src/models/profile.js~Profile.html#instance-member-lastName",
    "src/models/profile.js~Profile#lastName",
    "member"
  ],
  [
    "src/models/profile.js~profile#macros",
    "class/src/models/profile.js~Profile.html#instance-member-macros",
    "src/models/profile.js~Profile#macros",
    "member"
  ],
  [
    "src/models/profile.js~profile#setfemale",
    "class/src/models/profile.js~Profile.html#instance-method-setFemale",
    "src/models/profile.js~Profile#setFemale",
    "method"
  ],
  [
    "src/models/profile.js~profile#setmale",
    "class/src/models/profile.js~Profile.html#instance-method-setMale",
    "src/models/profile.js~Profile#setMale",
    "method"
  ],
  [
    "src/models/profile.js~profile#sex",
    "class/src/models/profile.js~Profile.html#instance-member-sex",
    "src/models/profile.js~Profile#sex",
    "member"
  ],
  [
    "src/models/profile.js~profile#weight",
    "class/src/models/profile.js~Profile.html#instance-member-weight",
    "src/models/profile.js~Profile#weight",
    "member"
  ],
  [
    "src/models/profile.js~user",
    "typedef/index.html#static-typedef-User",
    "src/models/profile.js~User",
    "typedef"
  ],
  [
    "src/models/volume.js",
    "file/src/models/volume.js.html",
    "src/models/volume.js",
    "file"
  ],
  [
    "src/models/volume.js~calorie",
    "typedef/index.html#static-typedef-Calorie",
    "src/models/volume.js~Calorie",
    "typedef"
  ],
  [
    "src/models/volume.js~trainingvolume",
    "typedef/index.html#static-typedef-TrainingVolume",
    "src/models/volume.js~TrainingVolume",
    "typedef"
  ],
  [
    "src/services/bmr.js",
    "file/src/services/bmr.js.html",
    "src/services/bmr.js",
    "file"
  ],
  [
    "src/services/bmr.js~bmr",
    "typedef/index.html#static-typedef-Bmr",
    "src/services/bmr.js~Bmr",
    "typedef"
  ],
  [
    "src/services/index.js",
    "file/src/services/index.js.html",
    "src/services/index.js",
    "file"
  ],
  [
    "src/services/macros.js",
    "file/src/services/macros.js.html",
    "src/services/macros.js",
    "file"
  ],
  [
    "src/services/macros.js~macros",
    "typedef/index.html#static-typedef-Macros",
    "src/services/macros.js~Macros",
    "typedef"
  ]
]